version: '3.8'
services:
  unified-app:
    build: .
    container_name: raff-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27020/mydb
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=mysecret
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27020:27020"

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
